### ISSUE TITLE
Please don't use chromium as webengine

### ISSUE THREAD

**Issue by behdanisohrab** [blackboardsh/electrobun#18]
Hi, 
please dont use chromium as webengine because of this two things:

1- binary size
2- don't became second electron :D

**Comment by kravetsone** [comment]
Please read README before opening issues

**Comment by YoavCodes** [comment]
@behdanisohrab I think our Discord would have been a better place for this.

But just to clarify here for others that look for this info via github issue and would like a more detailed explanation:
- We plan to always have Electrobun use the system webview by default
- It doesn't _really_ matter for binary size since Electrobun's smart bsdiff-based update mechanism means your app's updates are as small as 4KB regardless of the initial binary size, and our zstd-based self-extracting mechanism means your initial binary sizes are squeezed as small as possible.
- MANY people want the **option** to use a consistent renderer including pinning the version to mitigate the amount of work they need to do to make advanced web-apps cross platform. Even when I explain the security tradeoffs they are insistent and fine making that tradeoff and really want this option. Most of these cases exist today as webapps that only support chromium because startups tend not to have infinite resources and that's the most widely used renderer. And they'd really love to be able to extend into desktop apps without having to deal with a ton of cross-browser issues. So we do still intend to support this option.
- on Windows the system webview is Edge, which is Chromium. So I'm not sure I even understand your actual request.

I do appreciate your contribution though so thank you for taking the time to raise your concerns.

![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbHE4N2Y5YzEzOGlpOTZyaDZvd2ozMWRmenp6a2h5dGYwcm4zdDNmYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/uWlpPGquhGZNFzY90z/giphy.gif)
